site_name: Isolate
theme_dir: theme
pages:
  - Home: index.md
  - Isolate: isolate/isolate.md
  - Unit of Work:
    - Getting Started: unit-of-work/getting-started.md
    - Entity Definition: unit-of-work/entity-definition.md
    - Entity Internal States: unit-of-work/entity-internal-states.md
    - Command Handlers: unit-of-work/command-handlers.md
    - Associations: unit-of-work/associations.md
  - Lazy Objects:
    - Getting Started: lazy-objects/getting-started.md
    - Proxy Definition: lazy-objects/proxy-definition.md
    - Initializers: lazy-objects/initializers.md
    - Replacements: lazy-objects/replacements.md
  - Symfony: 
    - Installation and configuration: symfony/installation-and-configuration.md
    - Transaction Factories: symfony/transaction-factories.md
    - Usage Examples: symfony/usage-examples.md
    - Doctrine Bridge: symfony/doctrine-bridge.md
  - Doctrine:
    - Bridge: doctrine/bridge.md
theme: readthedocs
use_directory_urls: false
