site_name: Isolate
theme_dir: theme
pages:
  - ['index.md', 'Home']
  - ['isolate/isolate.md', 'Isolate']
  - ['unit-of-work/getting-started.md', 'Unit of Work', 'Getting Started']
  - ['unit-of-work/entity-definition.md', 'Unit of Work', 'Entity Definition']
  - ['unit-of-work/entity-internal-states.md', 'Unit of Work', 'Entity Internal States']
  - ['unit-of-work/command-handlers.md', 'Unit of Work', 'Command Handlers']
  - ['unit-of-work/associations.md', 'Unit of Work', 'Associations']
  - ['lazy-objects/getting-started.md', 'Lazy Objects', 'Getting Started']
  - ['lazy-objects/proxy-definition.md', 'Lazy Objects', 'Proxy Definition']
  - ['lazy-objects/initializers.md', 'Lazy Objects', 'Initializers']
  - ['lazy-objects/replacements.md', 'Lazy Objects', 'Replacements']
  - ['symfony/installation-and-configuration.md', 'Symfony', 'Installation and configuration']
  - ['symfony/transaction-factories.md', 'Symfony', 'Transaction Factories']
  - ['symfony/usage-examples.md', 'Symfony', 'Usage Examples']
  - ['symfony/doctrine-bridge.md', 'Symfony', 'Doctrine Bridge']
  - ['doctrine/bridge.md', 'Doctrine', 'Bridge']
theme: readthedocs
use_directory_urls: false
